version: '3'

services:
  website:
    build: .
    container_name: website
    restart: unless-stopped
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.tls=true
      - traefik.http.routers.website.tls.certresolver=lets-encrypt
      - traefik.http.routers.website.rule=Host(`liammahoney.io`)

networks:
  web:
    external: true
